---
title: "EDS 231: Assignment 2"
author: "Juliet Cohen, Charles Hendrickson,Scout Leonard, Peter Menzies"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: pdf_document
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(jsonlite)  
library(tidyverse) 
library(tidytext) 
library(here)
library(LexisNexisTools)
library(tidytext)
library(sentimentr)

requery <- TRUE
```

# Download Data

## Three Mile Island Accident data

```{r three mile data}
threemileisland_files <- list.files(pattern = ".docx",
                                    path = here("data/threemileisland"),
                                    full.names = TRUE,
                                    recursive = TRUE,
                                    ignore.case = TRUE)

threemileisland_data <- lnt_read(threemileisland_files) #Object of class 'LNT output'

threemileisland_meta_df <- threemileisland_data@meta %>% 
  rename(Art_ID = ID)

threemileisland_articles_df <- threemileisland_data@articles

threemileisland_paragraphs_df <- threemileisland_data@paragraphs

#joined df with paraagraphs and dates 
threemileisland_df <- full_join(threemileisland_paragraphs_df,
                                threemileisland_meta_df)
```

## Chernobyl disaster data

```{r chernobyl data}
chernobyl_files <- list.files(pattern = ".docx",
                              path = here("data/chernobyl"),
                              full.names = TRUE,
                              recursive = TRUE,
                              ignore.case = TRUE)

chernobyl_data <- lnt_read(chernobyl_files) #Object of class 'LNT output'

chernobyl_meta_df <- chernobyl_data@meta
chernobyl_articles_df <- chernobyl_data@articles
chernobyl_paragraphs_df <- chernobyl_data@paragraphs

chernobyl_df<- data_frame(element_id = seq(1:length(chernobyl_meta_df$Headline)),
                                Date = chernobyl_meta_df$Date,
                                Headline = chernobyl_meta_df$Headline)
```

## Fukashima disaster data

```{r fukashima data}
fukashima_files <- list.files(pattern = ".docx",
                         path = here("data/fukashima"),
                         full.names = TRUE,
                         recursive = TRUE,
                         ignore.case = TRUE)

fukashima_data <- lnt_read(fukashima_files) #Object of class 'LNT output'

fukashima_meta_df <- fukashima_data@meta
fukashima_articles_df <- fukashima_data@articles
fukashima_paragraphs_df <- fukashima_data@paragraphs

chernobyl_df<- data_frame(element_id = seq(1:length(fukashima_meta_df$Headline)),
                                Date = fukashima_meta_df$Date,
                                Headline = fukashima_meta_df$Headline)
```

## Sentiment time series

Read in sentiment analysis Lexicon:

```{r}
bing_sent <- get_sentiments('bing')
```

### Three Mile Island disaster

```{r}
#get sentences from three mile island paragraphs
threemileisland_text <- get_sentences(threemileisland_df$Paragraph)

#get sentiment from each sentence
threemileisland_sent <- sentiment(threemileisland_text)
# 
# threemileisland_df <- threemileisland_df %>% 
#   mutate(element_id = 1:length(threemileisland_df$Art_ID))

threemileisland_sent <- inner_join(threemileisland_df, 
                                   threemileisland_sent,
                                   by = c("Par_ID" = "element_id")) %>% 
  select(c("Par_ID", "sentiment", "Paragraph", "Date", "Newspaper"))
```

```{r}
# catgorize for ggplot
threemileisland_sent <- threemileisland_sent %>%
  mutate(sent_category = case_when(
    sentiment < 0 ~ "negative",
    sentiment == 0 ~ "neutral",
    sentiment > 0 ~ "positive"
  ))

head(threemileisland_sent, 5) %>% 
  kable()

#generate counts of sentiment sentences by date to plot
threemileisland_sent_plot <- threemileisland_sent %>%
  count(sent_category, Date)

#plot it UP
threemileisland_date <- which(threemileisland_df$Date %in% as.Date("1978-03-28"))

ggplot(data = threemileisland_sent_plot, aes(x = Date, y = n)) +
         geom_line(aes(color = sent_category)) +
  theme_minimal() +
  labs(y = "Developed Media Sentiment (no. headlines)",
       x = "Date",
       title = "Three Mile Island Publication Text Sentiment Analysis") +
  scale_color_manual(values = c("blue", "grey", "red")) +
  theme(plot.title = element_text(size = 20, hjust = 0.5),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 10)) +
  geom_vline(xintercept = as.numeric(threemileisland_df$Date[threemileisland_date]),
             col = "black")
```

### Chernobyl disaster

### Fukashima disaster 
